# O nome do ambiente de desenvolvimento para este projeto.
name: fiap_tech_challenge_2

# Os canais onde o Conda deve procurar pacotes, em ordem de prioridade.
# conda-forge no topo é a prática recomendada para maior consistência.
channels:
  - conda-forge
  - defaults

# A lista de dependências diretas e essenciais do seu projeto.
# Mantenha esta lista limpa e adicione apenas o que for realmente necessário.
dependencies:
  - python=3.11
  - numpy
  - pygame
  - matplotlib
  - openpyxl
